### ISSUE TITLE
HACS repository problem

### ISSUE THREAD

**Issue by zanac** [kandsten/ha-heatmap-card#10]
Please check, HACS repository seems be lost

**Comment by kandsten** [comment]
The card hasn't been added to HACS main repo, rather using the custom repo functionality. If you visit the [custom HACS repo link](https://my.home-assistant.io/redirect/hacs_repository/?owner=kandsten&repository=ha-heatmap-card&category=Lovelace) does it load for you?

**Comment by zanac** [comment]
ok, with custom hacs it work. thank.

**Comment by hundehausen** [comment]
Hey @kandsten 

I still have this issue:

`This will add the custom repository 'kandsten/ha-heatmap-card' to be tracked by HACS, do you want to add it?`

and then I click 'Add'

and in the next step it says 

`Repository kandsten/ha-heatmap-card not found`

**Comment by ethzero** [comment]
> Hey @kandsten 
> 
> I still have this issue:
> 
> `This will add the custom repository 'kandsten/ha-heatmap-card' to be tracked by HACS, do you want to add it?`
> 
> and then I click 'Add'
> 
> and in the next step it says 
> 
> `Repository kandsten/ha-heatmap-card not found`

+1 using the "custom HACS repo link" above.

**Comment by luebbe** [comment]
The problem still persists for me, I get exactly the error same messages using the custom HACS link above. Is it possible that HA handles custom repositories differently in the mean time?
