### ISSUE TITLE
Please add a rainbow map

### ISSUE THREAD

**Issue by zanac** [kandsten/ha-heatmap-card#11]
It's very nice when themperature is cool show "blue", when is spring "green" and when become summer "yellow" or "red"... a rainbow map like this can be much more fine:
https://blendcommerce.com/blogs/shopify/heatmaps-how-a-game-of-hot-and-cold-can-help-grow-your-website

**Comment by kandsten** [comment]
That's a fairly classic color scale indeed. I have a backlog/wishlist of stuff to add, some additional scales are a part of that.

**Comment by zanac** [comment]
> That's a fairly classic color scale indeed. I have a backlog/wishlist of stuff to add, some additional scales are a part of that.

maybe the best thing is to expose a sort of scales.json in which users can add custom scales....

**Comment by zanac** [comment]
I close this in favour of absolute scale (i opened an issue on that problem).
