### ISSUE TITLE
"Cannot assign to read only property "value" of object '#<object>"

### ISSUE THREAD

**Issue by NLKLVL2** [kandsten/ha-heatmap-card#15]
![Capture](https://github.com/kandsten/ha-heatmap-card/assets/140164737/3bdf6d52-cc72-4421-81b5-8d4b8a700427)

Hello, thank you for your heatmap is very usefull. Thank you for your work.
I have an issue with custom colors (see capture)
Could you help us or code the custom color front-end ^^ 

Thank you again !!!

**Comment by markuswizard** [comment]
I'm having the same problem.

**Comment by kandsten** [comment]
Apologies for the absurdly late attention from my side. I do believe that #16 fixes it indeed, kudos to @Hypfer

**Comment by tyriis** [comment]
could you please create a new build?
